{{- if and .Values.hackclean }}
{{ $component := hackclean }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-{{ $component }}
  labels:
    app: {{ template "prometheus-operator.name" . }}-{{ $component }}
{{ include "prometheus-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
{{- end }}
